pipeline{
    agent any
    environment{
        VERSION = "1.${BUILD_ID}"
        rollback = 'false'
        dockerhubcredentials = credentials('docker-hub-credentials')
        TEST_DATABASE_URI = "sqlite:///data.db"
        TEST_SECRET_KEY = "test"
      //  CHROMEDRIVER_PATH = "/home/jenkins/chromedriver"
        //AUTHOR = credentials("AUTHOR")
        DATABASE_URI = credentials("DATABASE_URI")
        SECRET_KEY = credentials("SECRET_KEY")
    }
    stages{
        stage("Test Stage"){
            steps{
                sh " cd testing && bash run_pytest.sh"
            }
        } 
            
        stage('Build App'){
            steps{
                sh "docker-compose build --parallel"
            }
        }
        stage('Push App to Docker-Hub'){
            steps{
                sh "docker login -u ${dockerhubcredentials_USR} -p ${dockerhubcredentials_PSW}"
                sh "docker-compose push"
            }
        }      
          stage("Configure Docker Swarm"){
            steps{
            //////    sh "bash jenkins/ansible-script/install-ansible.sh "
                sh "sudo su jenkins && cd jenkins/ansible-script && /home/jenkins/.local/bin/ansible-playbook -i inventory playbook.yaml"
            }
            }
            stage("Deploy application Stack"){
            steps{
                sh "bash jenkins/ansible-script/deploy_stack.sh"
            }
            }
    }
}
